
import { PriorityLevel } from './types';

export const PRIORITY_COLORS: Record<PriorityLevel, { bg: string; text: string; border: string }> = {
  [PriorityLevel.Low]: {
    bg: 'bg-sky-100',
    text: 'text-sky-800',
    border: 'border-sky-300',
  },
  [PriorityLevel.Medium]: {
    bg: 'bg-amber-100',
    text: 'text-amber-800',
    border: 'border-amber-300',
  },
  [PriorityLevel.High]: {
    bg: 'bg-orange-100',
    text: 'text-orange-800',
    border: 'border-orange-300',
  },
  [PriorityLevel.Critical]: {
    bg: 'bg-red-100',
    text: 'text-red-800',
    border: 'border-red-300',
  },
};

export const PROJECT_NAMES = [
  'Lake Lofts',
  'Gladiolus',
  'Kakoli',
  'Platinum',
  'Jardin Palacia',
  'Sahera Khatun',
  'Kolatia',
  'Ark-ology',
  'Simeen Court',
  'Hazratpur',
  'Ratan Kutir',
  'Helena Sparta',
  'Zaid Zodiac',
  'Bella Vista',
  '23/660 Dhanmondi-32',
  'Oleander',
  'Shantir Neer',
  'Paramount Residences',
  'Dhulikona',
  'Sterling',
  'Daisy Garden',
  'Rosewood',
  'Park Snowflake',
  'Carnation',
  'Noor Park',
  'Moonflower',
  'Moon Flower 4 Port',
  'Splendora',
  'Celestial',
  'Cherry Blossom',
  '6/5 Salaamun',
  'Rosali',
  '5/9 Block-C, Lalmatia',
  'Springdale',
  'Bougainvillea',
  'Forum Glory 3/11',
  'Hasnahena',
  'Golden Guinea',
  'Crown Park',
  '3/3 Park Jovial',
  'Tubaneer',
  'Roman Legacy',
  'Park Splendour',
  'Oshan',
  'Castle Onamika',
  'Park Riviera',
  'Park Periwinkle',
  'Sojourn',
  'Crowning Glory',
  'AK Paradise',
  'Pristine',
  'Mande Villa Laxa',
  'Vintage Vista',
  'RK Mission Road',
];