
export const ZONES = [
  'Dhanmondi',
  'Lalmatia',
  'Mohammadpur',
  'Kalabagan',
  'Banani',
  'Uttara',
  'Bosila',
  'Badda',
  "Cox's Bazar",
  'Kalatia',
];

export const DEPARTMENTS = [
  'Accounts & Finance',
  'Bill of Quantity (BoQ)',
  'Billing & Coordination',
  'Brand Management',
  'Construction',
  'Credence Design & Decor',
  'Customer Service',
  'Electro-Mechanical',
  'HR & Admin',
  'Information Technology (IT)',
  'Internal Audit',
  'Inventory Management',
  'LAW',
  'Logistics',
  'Management Information System (MIS)',
  'Material Quality Assurance & Purchase',
  'Planning & Design (Architectural)',
  'Planning & Design (Structural)',
  'Planning & Development',
  'Planning & Investment',
  'Quality Assurance',
  'Revenue Collection',
  'Security Management (HR)',
];

export const DESIGNATIONS = [
  'Manager',
  'Executive',
  'AGM',
  'AGM',
  'AGM',
  'D.M',
  'Asst. Manager [for construction]',
  'Sr. Manager',
  'Manager',
  'Asst. Manager',
  'Executive',
  'Security Supervisor',
  'Security Supervisor',
  'Security Supervisor',
  'Security Supervisor',
  'Security Supervisor',
  'Security Supervisor',
  'Security Supervisor',
  'Security Supervisor',
  'Security Supervisor',
  'Security Supervisor',
  'Security Supervisor',
  'Security Supervisor',
  'Security Supervisor [For HR & Admin (Security)]',
  'AGM',
  'Senior Executive',
  'Executive',
  'Junior Executive',
  'Electrician',
  'Electrician',
  'Electrician',
  'Electrician [for Electro-Mechanical]',
  'Senior Executive',
  'IT Technician',
  'IT Technician',
  '[for Information technology]',
  'Deputy Manager',
  'Asst. Manager',
  'Asst. Manager',
  'Asst. Manager',
  'Senior Executive',
  'Sr. Executive',
  'Sr. Executive',
  'Site Accountant (CH)',
  'Assistant Project Accountant (CH)',
  'Assistant Project Accountant (CH)',
  'Assistant Project Accountant (CH)',
  'Assistant Project Accountant (CH)',
  'Assistant Project Accountant (CH)',
  'Assistant Project Accountant (CH)',
  'Assistant Project Accountant (CH) [for Inventory Mgt.]',
  'Head of Procurement',
  'Assistant Manager',
  'Manager',
  'Senior Executive',
  'Senior Executive',
  'Executive',
  'Executive',
  'Executive',
  'Junior Executive',
  'Junior Executive',
  'Junior Executive [for Material Quality Assurance & Purchase]',
  'Associate Architect',
  'Senior Assistant Architect',
  'Assistant Architect',
  'Junior Architect',
  'Junior Architect',
  'Junior Architect',
  'Junior Architect',
  'Junior Architect',
  'Junior Architect',
  'Junior Architect [for Planning & Design (Architectural)]',
  'Manager',
  'Asst. Manager',
  'Sr. Executive [Quality Assurance]',
];
